name: 'data_modelling_case'

config-version: 2
version: '0.1'

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

vars:
  # Additional DBT vars to pass to the project
  # is_valid: true
  # processing_platform: 'skynet_v1.0.0'

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  data_modelling_case:
      marts:
        materialized: table
        +schema: marts
        +dist: auto
        +persist_docs:
          relation: true
          columns: true
        +meta:
          tech-owner: email.com
          business-owner: email.com
      staging:
        materialized: table
        +schema: staging
        +dist: auto
        +persist_docs:
          relation: true
          columns: true
        +meta:
          tech-owner: email.com
          business-owner: email.com
