# TODO: entrypoint doesn't work
services:
  postgres:
    image: postgres:15
    container_name: postgres_${PGDATABASE}
    restart: always
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
    # entrypoint: >
    #     "psql -h postgres -U ${PGUSER} -d ${PGDATABASE} -f admin-db-init/init.sql --set=pgdatabase=${PGDATABASE}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../init.sql:/admin-db-init/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
